[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FFC400"
backgroundColor = "#0D1720"
secondaryBackgroundColor = "#151F28"
textColor = "#F6F8FA"
font = "sans serif"
